export ZSH_CONFIG="$XDG_CONFIG_HOME/zsh"
export ZSH_CACHE="$XDG_CACHE_HOME/zsh"

# ZSH config files to be loaded
typeset -ga sources

sources+="$ZSH_CONFIG/environment.zsh"
sources+="$ZSH_CONFIG/options.zsh"
sources+="$ZSH_CONFIG/prompt.zsh"
sources+="$ZSH_CONFIG/functions.zsh"
sources+="$ZSH_CONFIG/aliases.zsh"
sources+="$ZSH_CONFIG/bindkeys.zsh"
sources+="$ZSH_CONFIG/completion.zsh"

# Load ZSH config files
foreach file (`echo $sources`)
    if [[ -a $file ]]; then
        source $file
    fi
end

